language: php

php:
  - '5.5'
  - '5.6'
  - '7.0'

install:
  - curl -s https://getcomposer.org/installer | php
  - php composer.phar install --prefer-dist -o

script: vendor/bin/phpunit -c tests/ tests/
