language: php

php:
  - '5.5'
  - '5.6'
  - '7.0'

env:
  - SYMFONY_VERSION="2.3.*"
  - SYMFONY_VERSION="2.7.*"
  - SYMFONY_VERSION="3.0.*"

install:
  - curl -s https://getcomposer.org/installer | php
  - php composer.phar require symfony/symfony:${SYMFONY_VERSION}

script: vendor/bin/phpunit -c tests/ tests/
